<a href="https://colab.research.google.com/github/skhetrapal/practise_codes/blob/main/NN_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Neural Networks using python basic libraries**

## The following functions are the building blocks to write NN

In [ ]:
import math
import numpy as np


In [ ]:
#sigmoid function
def sigmoid(x):
  s = 1/(1+ np.exp(-x))
  return s

#sigmoid derivative
def sigmoid_deriv(x):
  s = sigmoid(x)
  ds = s*(1-s)
  return ds

In [ ]:
t_x = np.array([1, 2, 3])
print(sigmoid(t_x))
print(sigmoid_deriv(t_x))

[0.73105858 0.88079708 0.95257413]
[0.19661193 0.10499359 0.04517666]


In [ ]:
#reshaping array to a vector
## images have shape: (length, height, 3), the last dimension stores RGB values for each image cell
def image2vec(image):
  v = image.reshape(image.shape[0]*image.shape[1]*image.shape[2],1) #coulf also use .reshape(-1,1)
  return v

In [ ]:
# flatten array to a vector
# given test set of number of examples m_train =209, training set of images is of shape (209,64,64,3)
train_set_x_flatten = train_set_x_orig.reshape(train_set_x_orig.shape[0],-1).T #shape = (12288, 209)
#train_set_x_orig.reshape(train_set_x_orig.shape[0],-1) gives array of shape (it's transpose gives the final result above)

NameError: name 'train_set_x_orig' is not defined

In [ ]:
t_image = np.array([[[ 0.67826139,  0.29380381],
                     [ 0.90714982,  0.52835647],
                     [ 0.4215251 ,  0.45017551]],

                   [[ 0.92814219,  0.96677647],
                    [ 0.85304703,  0.52351845],
                    [ 0.19981397,  0.27417313]],

                   [[ 0.60659855,  0.00533165],
                    [ 0.10820313,  0.49978937],
                    [ 0.34144279,  0.94630077]]])

print(image2vec(t_image))

[[0.67826139]
 [0.29380381]
 [0.90714982]
 [0.52835647]
 [0.4215251 ]
 [0.45017551]
 [0.92814219]
 [0.96677647]
 [0.85304703]
 [0.52351845]
 [0.19981397]
 [0.27417313]
 [0.60659855]
 [0.00533165]
 [0.10820313]
 [0.49978937]
 [0.34144279]
 [0.94630077]]


In [ ]:
#normalising rows of a matrix
def normalize_rows(x):
  x_norm = np.linalg.norm(x,axis=1,keepdims=True) #for columns use axis = 0
  x = x/x_norm

  return x

In [ ]:
x = np.array([[0, 3, 4],
              [1, 6, 4]])
print(normalize_rows(x))

[[0.         0.6        0.8       ]
 [0.13736056 0.82416338 0.54944226]]


In [ ]:
#softmax function
def softmax(x):
  x_exp = np.exp(x)
  x_exp_sum = np.linalg.norm(x_exp, axis=1,keepdims=True)
  s = x_exp/x_exp_sum
  return s

In [ ]:
t_x = np.array([[9, 2, 5, 0, 0],
                [7, 5, 0, 0 ,0]])
print(softmax(t_x))

[[9.99831880e-01 9.11728660e-04 1.83125597e-02 1.23389056e-04
  1.23389056e-04]
 [9.90964875e-01 1.34112512e-01 9.03642998e-04 9.03642998e-04
  9.03642998e-04]]


In [ ]:
x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]

##vectorised dot product
dot = np.dot(x1,x2) #np.matmul for matrices
print(dot)

##vectorised outer product
outer = np.outer(x1,x2)
print(outer)

##vectorised elementwise multipliclation
elementwise = np.multiply(x1,x2)
print(elementwise)

278
[[81 18 18 81  0 81 18 45  0  0 81 18 45  0  0]
 [18  4  4 18  0 18  4 10  0  0 18  4 10  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [63 14 14 63  0 63 14 35  0  0 63 14 35  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [81 18 18 81  0 81 18 45  0  0 81 18 45  0  0]
 [18  4  4 18  0 18  4 10  0  0 18  4 10  0  0]
 [45 10 10 45  0 45 10 25  0  0 45 10 25  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]
[81  4 10  0  0 63 10  0  0  0 81  4 25  0  0]


In [ ]:
# L1, L2, cross-entropy loss

## L1 loss
def L1(yhat, y):
  loss = np.sum(np.absolute(y-yhat))
  return loss

## L2 loss
def L2(yhat, y):
  loss = np.sum(np.dot(yhat-y,yhat-y))
  return loss

## cross_entropy_cost
def cross_entropy_loss(a,y):
  #y is of shape (1,number of examples)
  #m = y.shape[1]
  loss = -np.sum(np.dot(y,np.log(a).T)+np.dot(1-y,np.log(1-a).T))
  return loss

In [ ]:
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])

print(L1(yhat,y))
print(L2(yhat,y))
print(cross_entropy_loss(yhat,y))

1.1
0.43
1.4555158301618436


## Logistic Regression as Neural Network

In [ ]:
#initialize parameters w, b
def initialize(dim):
  w = np.rand.randn((dim,1))*0.001 #since w is a vector #
  b = 0. #since b is a number

In [ ]:
#forward propagation
def propagate(w,b,X,Y):
  # X is data of size (num_px*num_px*3, number of examples)
  m = X.shape[1] #number of examples
  A = sigmoid(np.dot(w.T,X)+b)
  cost = (-1/m)*cross_entropy_loss(A,Y)
  cost = np.squeeze(np.array(cost))

  #backprop
  dZ = A-Y
  dw = (1/m)*np.dot(X,dZ.T)
  db = (1/m)*np.sum(dZ)

  grads = {"dw": dw,
           "db": db}

  return grads,cost


In [ ]:
#optimization function to run the update rule for parameters
def optimize(w, b, X, Y, num_iterations=100, learning_rate=0.009, print_cost=False):
  w = copy.deepcopy(w)
  b = copy.deepcopy(b)

  costs = []

  for i in range(num_iterations):
    grads, cost = propagate(w,b,X,Y)

    dw, db = grads["dw"], grads["db"]

    w = w - learning_rate*dw
    b = b - learning_rate*db

    if i % 100 == 0:
      costs.append(cost)
      # Print the cost every 100 training iterations
      if print_cost:
        print("Cost after iteration %i: %f" %(i, cost))

  params = {"w": w,
              "b": b}

  grads = {"dw": dw,
             "db": db}

  return params, grads, costs

In [ ]:
#predict
def predict(w, b, X):
  m = X.shape[1] #m = number of examples in X, X has shape (num_px*num_px*3,m)
  Y_prediction = np.zeros((1, m))
  w = w.reshape(X.shape[0], 1) #making sure w is the correct shape

  A = sigmoid(np.dot(w.T,X)+b) #shape (1,m)

  for i in range(A.shape[1]):
    if A[0, i] > 0.5 :
             Y_prediction[0,i] = 1
    else:
             Y_prediction[0,i] = 0

  return Y_prediction

In [ ]:
#putting the model together
def model(X_train, Y_train, X_test, Y_test, num_iterations=2000, learning_rate=0.5, print_cost=False):
  w, b = initialize(X_train.shape[0])
  params, grads, costs = optimize(w, b, X_train, Y_train, num_iterations, learning_rate, print_cost)
  w = params["w"]
  b = params["b"]
  Y_prediction_test = predict(w, b, X_test)
  Y_prediction_train = predict(w, b, X_train)

  d = {"costs": costs,
         "Y_prediction_test": Y_prediction_test,
         "Y_prediction_train" : Y_prediction_train,
         "w" : w,
         "b" : b,
         "learning_rate" : learning_rate,
         "num_iterations": num_iterations}

  return d

In [ ]:
import h5py

def load_dataset():
    train_dataset = h5py.File('https://github.com/skhetrapal/ML-DL-labs/blob/main/Deep%20Learning/NN_basics/Files_1_2/home/jovyan/work/release/W2A2/datasets/train_catvnoncat.h5', "r")
    train_set_x_orig = np.array(train_dataset["train_set_x"][:]) # your train set features
    train_set_y_orig = np.array(train_dataset["train_set_y"][:]) # your train set labels

    test_dataset = h5py.File('https://github.com/skhetrapal/ML-DL-labs/blob/main/Deep%20Learning/NN_basics/Files_1_2/home/jovyan/work/release/W2A2/datasets/test_catvnoncat.h5', "r")
    test_set_x_orig = np.array(test_dataset["test_set_x"][:]) # your test set features
    test_set_y_orig = np.array(test_dataset["test_set_y"][:]) # your test set labels

    classes = np.array(test_dataset["list_classes"][:]) # the list of classes

    train_set_y_orig = train_set_y_orig.reshape((1, train_set_y_orig.shape[0]))
    test_set_y_orig = test_set_y_orig.reshape((1, test_set_y_orig.shape[0]))

    return train_set_x_orig, train_set_y_orig, test_set_x_orig, test_set_y_orig, classes

train_set_x_orig, train_set_y, test_set_x_orig, test_set_y, classes = load_dataset()
train_set_x_flatten = train_set_x_orig.reshape(train_set_x_orig.shape[0],-1).T
test_set_x_flatten = test_set_x_orig.reshape(test_set_x_orig.shape[0],-1).T

train_set_x = train_set_x_flatten / 255.
test_set_x = test_set_x_flatten / 255.

logistic_regression_model = model(train_set_x, train_set_y, test_set_x, test_set_y, num_iterations=2000, learning_rate=0.005, print_cost=True)


FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = 'https://github.com/skhetrapal/ML-DL-labs/blob/main/Deep%20Learning/NN_basics/Files_1_2/home/jovyan/work/release/W2A2/datasets/train_catvnoncat.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

## Batch, mini-batch and stochastic gradient descent

In [ ]:
#update_parameters_with_gd

def update_parameters_with_gd(parameters, grads, learning_rate):
  #parameters is a python dictionary parameters['W'+Str(l)] = Wl and similarly for b
  L = len(parameters//2) #number of layers in Neural Network

  for l in range(1,L+1):
    parameters["W" + str(l)] = parameters["W" + str(l)] - learning_rate * grads['dW' + str(l)]
    parameters["b" + str(l)] = parameters["b" + str(l)] - learning_rate * grads['db' + str(l)]

  return parameters

In [ ]:
#mini-batch gradient descent with random mini batches

def random_mini_batches(X, Y, mini_batch_size = 64, seed = 0):
  # X has shape (input size, number of examples)
  # Y has shape (1, number of examples)
  #np.random.seed(seed)           # to fix seed in case repeatability is required
  m = X.shape[1]                  # number of training examples
  mini_batches = []

  # Step 1: Shuffle (X, Y)
  permutation = list(np.random.permutation(m))
  shuffled_X = X[:, permutation] #keeping 'input size' dimension same, permuting over number of examples
  shuffled_Y = Y[:, permutation].reshape((1, m))

  inc = mini_batch_size

  num_complete_minibatches = math.floor(m / mini_batch_size) # number of mini batches of size mini_batch_size in your partitionning
  for k in range(0, num_complete_minibatches):
    mini_batch_X = shuffled_X[:,k * inc : (k+1) * inc]
    mini_batch_Y = shuffled_Y[:,k * inc : (k+1) * inc]
    mini_batch = (mini_batch_X, mini_batch_Y)
    mini_batches.append(mini_batch)

  # For handling the end case (last mini-batch < mini_batch_size i.e less than 64)
  if m % mini_batch_size != 0:
    mini_batch_X = shuffled_X[:, num_complete_minibatches * inc : num_complete_minibatches * inc + m - inc * math.floor(m/inc)]
    mini_batch_Y = shuffled_Y[:, num_complete_minibatches * inc : num_complete_minibatches * inc + m - inc * math.floor(m/inc)]
    mini_batch = (mini_batch_X, mini_batch_Y)
    mini_batches.append(mini_batch)

  return mini_batches